import {ReactComponent as Bookmark} from './BuyrutmalarImages/bookmark.svg';
import {ReactComponent as Clock} from './BuyrutmalarImages/clock.svg';
import {ReactComponent as User} from './BuyrutmalarImages/user.svg';
import {ReactComponent as Phone} from './BuyrutmalarImages/phone.svg';
import {ReactComponent as Oval} from './BuyrutmalarImages/Oval.svg';
import {ReactComponent as Clipboard} from './BuyrutmalarImages/clipboard.svg';
import {ReactComponent as Truck} from './BuyrutmalarImages/truck.svg';
import {ReactComponent as Deleted} from './BuyrutmalarImages/deleted.svg';
import {ReactComponent as Edited} from './BuyrutmalarImages/edit.svg';

export const Buyrutma = [
    {
        id:1,
        button:'8549',
        buttonIcon:<Bookmark />,
        timeIcon:<Clock />,
        timeValue:'00:24',
        userIcon:<User />,
        userName: `Jahongir`,
        userLastName:'Jumayev ',
        userPhoneIcon :<Phone />,
        userPhone:'+998911234567',
        productCostIcon:<Clipboard/>,
        productCost:'35400 UZS',
        paymeIcon:<Oval/>,
        payment:'Payme',
        deliverIcon:<Truck />,
        deliverCost:'5000 UZS',
        summaText:'Umumiy summa',
        summa:'40400 UZS',
        operatorText:'operator:',
        operatorName:"Kamilova M",
        branch:'Filial:',
        branchProductName:'Fast Food',
        branchName:'Maksim Gorkiy',
        delete:<Deleted/>,
        edit:<Edited/>,
    },
    {
        id:2,
        button:'8550',
        buttonIcon:<Bookmark />,
        timeIcon:<Clock />,
        timeValue:'00:30',
        userIcon:<User />,
        userName: `Jahongir`,
        userLastName:'Jumayev ',
        userPhoneIcon :<Phone />,
        userPhone:'+998911234567',
        productCostIcon:<Clipboard/>,
        productCost:'38500 UZS',
        paymeIcon:<Oval/>,
        payment:'Payme',
        deliverIcon:<Truck />,
        deliverCost:'10000 UZS',
        summaText:'Umumiy summa',
        summa:'45400 UZS',
        operatorText:'operator:',
        operatorName:"Jabborova K",
        branch:'Filial:',
        branchProductName:'Fast Food',
        branchName:'Chilanzor',
        delete:<Deleted/>,
        edit:<Edited/>,
    },
    {
        id:3,
        button:'10550',
        buttonIcon:<Bookmark />,
        timeIcon:<Clock />,
        timeValue:'01:30',
        userIcon:<User />,
        userName: `Jahongir`,
        userLastName:'Jumayev ',
        userPhoneIcon :<Phone />,
        userPhone:'+998911234567',
        productCostIcon:<Clipboard/>,
        productCost:'58500 UZS',
        paymeIcon:<Oval/>,
        payment:'Payme',
        deliverIcon:<Truck />,
        deliverCost:'12000 UZS',
        summaText:'Umumiy summa',
        summa:'65400 UZS',
        operatorText:'operator:',
        operatorName:"Ismoilov Sh",
        branch:'Filial:',
        branchProductName:'Fast Food',
        branchName:'Olmazor',
        delete:<Deleted/>,
        edit:<Edited/>,
    },
    {
        id:4,
        button:'9550',
        buttonIcon:<Bookmark />,
        timeIcon:<Clock />,
        timeValue:'02:30',
        userIcon:<User />,
        userName: `Jahongir`,
        userLastName:'Jumayev ',
        userPhoneIcon :<Phone />,
        userPhone:'+99890 588-99-86',
        productCostIcon:<Clipboard/>,
        productCost:'35500 UZS',
        paymeIcon:<Oval/>,
        payment:'Payme',
        deliverIcon:<Truck />,
        deliverCost:'11000 UZS',
        summaText:'Umumiy summa',
        summa:'45400 UZS',
        operatorText:'operator:',
        operatorName:"O'roqov A",
        branch:'Filial:',
        branchProductName:'Fast Food',
        branchName:'Yakkasaroy',
        delete:<Deleted/>,
        edit:<Edited/>,
    },
]